/**
 * BANCO DE PALAVRAS E DESENHOS  —  responsabilidade: Magno
 *
 * Cada item tem:
 *   id         -> identificador unico e estavel (NAO reaproveitar id de palavra removida,
 *                 porque o ranking e o historico guardam esse id no localStorage)
 *   palavra    -> a palavra em si, em MAIUSCULAS e com acento quando existir.
 *                 O jogo compara ignorando acento (ver normalizar() em sistemas/palavras.js),
 *                 entao escrever "MACA" ou "MAÇÃ" funciona igual pro jogador.
 *   categoria  -> usado pra filtrar rodadas por tema (ex.: so ANIMAIS)
 *   dificuldade-> 'facil' | 'medio' | 'dificil'
 *   emoji      -> o "desenho" da palavra. E ele que aparece embaixo e vai ficando nitido.
 *   dica       -> frase curta liberada quando o jogador pede ajuda
 *   imagem     -> (opcional) URL/caminho de imagem de verdade. Se existir, o componente
 *                 ImagemRevelada usa a imagem no lugar do emoji. Assim da pra trocar
 *                 emoji por desenho PNG/SVG depois sem mexer em mais nada.
 *
 * Regra que usei pra separar por dificuldade:
 *   facil   -> 4 a 6 letras, palavra do dia a dia, sem letra repetida esquisita
 *   medio   -> 6 a 9 letras, ou com acento/cedilha
 *   dificil -> 9+ letras, palavra composta, ou pouco comum
 */

export const CATEGORIAS = {
  ANIMAIS: 'Animais',
  COMIDAS: 'Comidas',
  OBJETOS: 'Objetos',
  NATUREZA: 'Natureza',
  TRANSPORTE: 'Transporte',
  ESPORTES: 'Esportes',
  PROFISSOES: 'Profissões',
  LUGARES: 'Lugares',
  ROUPAS: 'Roupas',
  TECNOLOGIA: 'Tecnologia',
}

export const PALAVRAS = [
  // ---------------------------------------------------------------- FÁCIL
  { id: 'f01', palavra: 'GATO',    categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'facil', emoji: '🐱', dica: 'Faz miau e dorme o dia inteiro' },
  { id: 'f02', palavra: 'CACHORRO',categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'facil', emoji: '🐶', dica: 'Melhor amigo do homem' },
  { id: 'f03', palavra: 'PEIXE',   categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'facil', emoji: '🐟', dica: 'Vive na água e tem escamas' },
  { id: 'f04', palavra: 'VACA',    categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'facil', emoji: '🐄', dica: 'Dá leite' },
  { id: 'f05', palavra: 'ABELHA',  categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'facil', emoji: '🐝', dica: 'Faz mel' },
  { id: 'f06', palavra: 'BOLO',    categoria: CATEGORIAS.COMIDAS,    dificuldade: 'facil', emoji: '🍰', dica: 'Não pode faltar no aniversário' },
  { id: 'f07', palavra: 'PIZZA',   categoria: CATEGORIAS.COMIDAS,    dificuldade: 'facil', emoji: '🍕', dica: 'Redonda, fatiada e italiana' },
  { id: 'f08', palavra: 'MACA',    categoria: CATEGORIAS.COMIDAS,    dificuldade: 'facil', emoji: '🍎', dica: 'Fruta vermelha do professor' },
  { id: 'f09', palavra: 'PAO',     categoria: CATEGORIAS.COMIDAS,    dificuldade: 'facil', emoji: '🍞', dica: 'Café da manhã básico' },
  { id: 'f10', palavra: 'OVO',     categoria: CATEGORIAS.COMIDAS,    dificuldade: 'facil', emoji: '🥚', dica: 'Vem antes ou depois da galinha?' },
  { id: 'f11', palavra: 'CASA',    categoria: CATEGORIAS.LUGARES,    dificuldade: 'facil', emoji: '🏠', dica: 'Onde você mora' },
  { id: 'f12', palavra: 'LIVRO',   categoria: CATEGORIAS.OBJETOS,    dificuldade: 'facil', emoji: '📚', dica: 'Tem páginas e história dentro' },
  { id: 'f13', palavra: 'RELOGIO', categoria: CATEGORIAS.OBJETOS,    dificuldade: 'facil', emoji: '⏰', dica: 'Marca as horas' },
  { id: 'f14', palavra: 'CHAVE',   categoria: CATEGORIAS.OBJETOS,    dificuldade: 'facil', emoji: '🔑', dica: 'Abre a porta' },
  { id: 'f15', palavra: 'SOL',     categoria: CATEGORIAS.NATUREZA,   dificuldade: 'facil', emoji: '☀️', dica: 'Estrela do nosso sistema' },
  { id: 'f16', palavra: 'LUA',     categoria: CATEGORIAS.NATUREZA,   dificuldade: 'facil', emoji: '🌙', dica: 'Aparece de noite' },
  { id: 'f17', palavra: 'ARVORE',  categoria: CATEGORIAS.NATUREZA,   dificuldade: 'facil', emoji: '🌳', dica: 'Tem tronco, folha e sombra' },
  { id: 'f18', palavra: 'CARRO',   categoria: CATEGORIAS.TRANSPORTE, dificuldade: 'facil', emoji: '🚗', dica: 'Tem quatro rodas e volante' },
  { id: 'f19', palavra: 'BARCO',   categoria: CATEGORIAS.TRANSPORTE, dificuldade: 'facil', emoji: '⛵', dica: 'Anda na água' },
  { id: 'f20', palavra: 'BOLA',    categoria: CATEGORIAS.ESPORTES,   dificuldade: 'facil', emoji: '⚽', dica: 'Rola e é chutada' },
  { id: 'f21', palavra: 'PATO',    categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'facil', emoji: '🦆', dica: 'Faz quá-quá e adora água' },
  { id: 'f22', palavra: 'RATO',    categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'facil', emoji: '🐭', dica: 'Pequeno, roedor, gosta de queijo' },
  { id: 'f23', palavra: 'URSO',    categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'facil', emoji: '🐻', dica: 'Grande, peludo, hiberna no frio' },
  { id: 'f24', palavra: 'LEAO',    categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'facil', emoji: '🦁', dica: 'Rei da selva' },
  { id: 'f25', palavra: 'SAPO',    categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'facil', emoji: '🐸', dica: 'Pula e vive perto da água' },
  { id: 'f26', palavra: 'GALO',    categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'facil', emoji: '🐓', dica: 'Canta de manhã cedo' },
  { id: 'f27', palavra: 'COBRA',   categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'facil', emoji: '🐍', dica: 'Não tem perna e se arrasta' },
  { id: 'f28', palavra: 'CAVALO',  categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'facil', emoji: '🐴', dica: 'Relincha e é usado pra montaria' },
  { id: 'f29', palavra: 'BANANA',  categoria: CATEGORIAS.COMIDAS,    dificuldade: 'facil', emoji: '🍌', dica: 'Fruta amarela e curva' },
  { id: 'f30', palavra: 'LARANJA', categoria: CATEGORIAS.COMIDAS,    dificuldade: 'facil', emoji: '🍊', dica: 'Fruta cítrica, dá suco' },
  { id: 'f31', palavra: 'UVA',     categoria: CATEGORIAS.COMIDAS,    dificuldade: 'facil', emoji: '🍇', dica: 'Vem em cacho, faz vinho' },
  { id: 'f32', palavra: 'LEITE',   categoria: CATEGORIAS.COMIDAS,    dificuldade: 'facil', emoji: '🥛', dica: 'Bebida branca, vem da vaca' },
  { id: 'f33', palavra: 'QUEIJO',  categoria: CATEGORIAS.COMIDAS,    dificuldade: 'facil', emoji: '🧀', dica: 'Cheio de furinhos às vezes' },
  { id: 'f34', palavra: 'ARROZ',   categoria: CATEGORIAS.COMIDAS,    dificuldade: 'facil', emoji: '🍚', dica: 'Combina com feijão' },
  { id: 'f35', palavra: 'FEIJAO',  categoria: CATEGORIAS.COMIDAS,    dificuldade: 'facil', emoji: '🫘', dica: 'Combina com arroz' },
  { id: 'f36', palavra: 'MEL',     categoria: CATEGORIAS.COMIDAS,    dificuldade: 'facil', emoji: '🍯', dica: 'Doce e feito pela abelha' },
  { id: 'f37', palavra: 'MESA',    categoria: CATEGORIAS.OBJETOS,    dificuldade: 'facil', emoji: '🪑', dica: 'Onde você coloca o prato pra comer' },
  { id: 'f38', palavra: 'CAMA',    categoria: CATEGORIAS.OBJETOS,    dificuldade: 'facil', emoji: '🛏️', dica: 'Onde você dorme' },
  { id: 'f39', palavra: 'COPO',    categoria: CATEGORIAS.OBJETOS,    dificuldade: 'facil', emoji: '🥤', dica: 'Serve pra beber água' },
  { id: 'f40', palavra: 'LAPIS',   categoria: CATEGORIAS.OBJETOS,    dificuldade: 'facil', emoji: '✏️', dica: 'Serve pra escrever ou desenhar' },
  { id: 'f41', palavra: 'BOLSA',   categoria: CATEGORIAS.OBJETOS,    dificuldade: 'facil', emoji: '👜', dica: 'Carrega as coisas quando você sai' },
  { id: 'f42', palavra: 'ESPELHO', categoria: CATEGORIAS.OBJETOS,    dificuldade: 'facil', emoji: '🪞', dica: 'Mostra seu reflexo' },
  { id: 'f43', palavra: 'VELA',    categoria: CATEGORIAS.OBJETOS,    dificuldade: 'facil', emoji: '🕯️', dica: 'Acende no bolo de aniversário' },
  { id: 'f44', palavra: 'CHUVA',   categoria: CATEGORIAS.NATUREZA,   dificuldade: 'facil', emoji: '🌧️', dica: 'Cai do céu quando tem nuvem escura' },
  { id: 'f45', palavra: 'NUVEM',   categoria: CATEGORIAS.NATUREZA,   dificuldade: 'facil', emoji: '☁️', dica: 'Branca, flutua no céu' },
  { id: 'f46', palavra: 'PRAIA',   categoria: CATEGORIAS.LUGARES,    dificuldade: 'facil', emoji: '🏖️', dica: 'Tem areia e mar' },
  { id: 'f47', palavra: 'ESCOLA',  categoria: CATEGORIAS.LUGARES,    dificuldade: 'facil', emoji: '🏫', dica: 'Onde você estuda' },
  { id: 'f48', palavra: 'PARQUE',  categoria: CATEGORIAS.LUGARES,    dificuldade: 'facil', emoji: '🎡', dica: 'Tem balanço e escorregador' },
  { id: 'f49', palavra: 'AVIAO',   categoria: CATEGORIAS.TRANSPORTE, dificuldade: 'facil', emoji: '✈️', dica: 'Voa alto e leva passageiros' },
  { id: 'f50', palavra: 'TREM',    categoria: CATEGORIAS.TRANSPORTE, dificuldade: 'facil', emoji: '🚆', dica: 'Anda sobre trilhos' },
  { id: 'f51', palavra: 'MOTO',    categoria: CATEGORIAS.TRANSPORTE, dificuldade: 'facil', emoji: '🏍️', dica: 'Duas rodas com motor' },
  { id: 'f52', palavra: 'ONIBUS',  categoria: CATEGORIAS.TRANSPORTE, dificuldade: 'facil', emoji: '🚌', dica: 'Leva muita gente de uma vez' },
  { id: 'f53', palavra: 'TENIS',   categoria: CATEGORIAS.ROUPAS,     dificuldade: 'facil', emoji: '👟', dica: 'Calçado pra correr' },
  { id: 'f54', palavra: 'CAMISA',  categoria: CATEGORIAS.ROUPAS,     dificuldade: 'facil', emoji: '👕', dica: 'Veste a parte de cima do corpo' },
  { id: 'f55', palavra: 'BONE',    categoria: CATEGORIAS.ROUPAS,     dificuldade: 'facil', emoji: '🧢', dica: 'Protege a cabeça do sol' },
  { id: 'f56', palavra: 'MEIA',    categoria: CATEGORIAS.ROUPAS,     dificuldade: 'facil', emoji: '🧦', dica: 'Veste antes do sapato' },
  { id: 'f57', palavra: 'LUVA',    categoria: CATEGORIAS.ROUPAS,     dificuldade: 'facil', emoji: '🧤', dica: 'Protege a mão do frio' },
  { id: 'f58', palavra: 'MOUSE',   categoria: CATEGORIAS.TECNOLOGIA, dificuldade: 'facil', emoji: '🖱️', dica: 'Você move ele pra mexer no cursor' },
  { id: 'f59', palavra: 'FONE',    categoria: CATEGORIAS.TECNOLOGIA, dificuldade: 'facil', emoji: '🎧', dica: 'Coloca no ouvido pra escutar música' },
  { id: 'f60', palavra: 'PILHA',   categoria: CATEGORIAS.TECNOLOGIA, dificuldade: 'facil', emoji: '🔋', dica: 'Dá energia pro controle remoto' },
  { id: 'f61', palavra: 'REMO',    categoria: CATEGORIAS.ESPORTES,   dificuldade: 'facil', emoji: '🚣', dica: 'Serve pra impulsionar o barco' },
  { id: 'f62', palavra: 'JUDO',    categoria: CATEGORIAS.ESPORTES,   dificuldade: 'facil', emoji: '🥋', dica: 'Luta japonesa com faixa colorida' },
  { id: 'f63', palavra: 'SURFE',   categoria: CATEGORIAS.ESPORTES,   dificuldade: 'facil', emoji: '🏄', dica: 'Anda em cima da onda' },
  { id: 'f64', palavra: 'NADO',    categoria: CATEGORIAS.ESPORTES,   dificuldade: 'facil', emoji: '🏊', dica: 'Esporte que se faz na piscina' },
  { id: 'f65', palavra: 'ATOR',    categoria: CATEGORIAS.PROFISSOES, dificuldade: 'facil', emoji: '🎭', dica: 'Trabalha atuando em filme ou peça' },
  { id: 'f66', palavra: 'PADEIRO', categoria: CATEGORIAS.PROFISSOES, dificuldade: 'facil', emoji: '🥖', dica: 'Faz o pão de cada dia' },
  { id: 'f67', palavra: 'PILOTO',  categoria: CATEGORIAS.PROFISSOES, dificuldade: 'facil', emoji: '🧑‍✈️', dica: 'Comanda o avião' },
  { id: 'f68', palavra: 'PALHACO', categoria: CATEGORIAS.PROFISSOES, dificuldade: 'facil', emoji: '🤡', dica: 'Faz a criançada rir no circo' },
  { id: 'f69', palavra: 'ESTRELA', categoria: CATEGORIAS.NATUREZA,   dificuldade: 'facil', emoji: '⭐', dica: 'Brilha no céu à noite' },
  { id: 'f70', palavra: 'MONTANHA',categoria: CATEGORIAS.NATUREZA,   dificuldade: 'facil', emoji: '⛰️', dica: 'Bem mais alta que uma colina' },

  // ---------------------------------------------------------------- MÉDIO
  { id: 'm01', palavra: 'ELEFANTE',    categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'medio', emoji: '🐘', dica: 'Tem tromba e orelha grande' },
  { id: 'm02', palavra: 'GIRAFA',      categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'medio', emoji: '🦒', dica: 'O pescoço mais famoso da savana' },
  { id: 'm03', palavra: 'PINGUIM',     categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'medio', emoji: '🐧', dica: 'Ave que nada mas não voa' },
  { id: 'm04', palavra: 'TARTARUGA',   categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'medio', emoji: '🐢', dica: 'Anda devagar com a casa nas costas' },
  { id: 'm05', palavra: 'MACACO',      categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'medio', emoji: '🐵', dica: 'Gosta de banana e galho' },
  { id: 'm06', palavra: 'MELANCIA',    categoria: CATEGORIAS.COMIDAS,    dificuldade: 'medio', emoji: '🍉', dica: 'Verde por fora, vermelha por dentro' },
  { id: 'm07', palavra: 'CHOCOLATE',   categoria: CATEGORIAS.COMIDAS,    dificuldade: 'medio', emoji: '🍫', dica: 'Derrete na mão e na boca' },
  { id: 'm08', palavra: 'SORVETE',     categoria: CATEGORIAS.COMIDAS,    dificuldade: 'medio', emoji: '🍦', dica: 'Gelado e some no calor' },
  { id: 'm09', palavra: 'ABACAXI',     categoria: CATEGORIAS.COMIDAS,    dificuldade: 'medio', emoji: '🍍', dica: 'Fruta com coroa' },
  { id: 'm10', palavra: 'GUARDACHUVA', categoria: CATEGORIAS.OBJETOS,    dificuldade: 'medio', emoji: '☂️', dica: 'Salva você da chuva (tudo junto, sem hífen)' },
  { id: 'm11', palavra: 'TELEFONE',    categoria: CATEGORIAS.OBJETOS,    dificuldade: 'medio', emoji: '📞', dica: 'Serve pra ligar pra alguém' },
  { id: 'm12', palavra: 'TESOURA',     categoria: CATEGORIAS.OBJETOS,    dificuldade: 'medio', emoji: '✂️', dica: 'Corta papel' },
  { id: 'm13', palavra: 'FOGUETE',     categoria: CATEGORIAS.TRANSPORTE, dificuldade: 'medio', emoji: '🚀', dica: 'Vai pro espaço' },
  { id: 'm14', palavra: 'BICICLETA',   categoria: CATEGORIAS.TRANSPORTE, dificuldade: 'medio', emoji: '🚲', dica: 'Duas rodas e pedal' },
  { id: 'm15', palavra: 'HELICOPTERO', categoria: CATEGORIAS.TRANSPORTE, dificuldade: 'medio', emoji: '🚁', dica: 'Voa com hélice em cima' },
  { id: 'm16', palavra: 'VULCAO',      categoria: CATEGORIAS.NATUREZA,   dificuldade: 'medio', emoji: '🌋', dica: 'Montanha que cospe lava' },
  { id: 'm17', palavra: 'CACHOEIRA',   categoria: CATEGORIAS.NATUREZA,   dificuldade: 'medio', emoji: '💦', dica: 'Água caindo lá do alto' },
  { id: 'm18', palavra: 'MEDICO',      categoria: CATEGORIAS.PROFISSOES, dificuldade: 'medio', emoji: '👨‍⚕️', dica: 'Trabalha de jaleco e cuida de gente doente' },
  { id: 'm19', palavra: 'BOMBEIRO',    categoria: CATEGORIAS.PROFISSOES, dificuldade: 'medio', emoji: '👨‍🚒', dica: 'Apaga incêndio' },
  { id: 'm20', palavra: 'BASQUETE',    categoria: CATEGORIAS.ESPORTES,   dificuldade: 'medio', emoji: '🏀', dica: 'Joga na cesta' },
  { id: 'm21', palavra: 'CROCODILO',   categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'medio', emoji: '🐊', dica: 'Boca grande cheia de dentes, vive no rio' },
  { id: 'm22', palavra: 'CANGURU',     categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'medio', emoji: '🦘', dica: 'Pula e carrega o filhote na bolsa' },
  { id: 'm23', palavra: 'COALA',       categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'medio', emoji: '🐨', dica: 'Dorme quase o dia todo agarrado no eucalipto' },
  { id: 'm24', palavra: 'CORUJA',      categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'medio', emoji: '🦉', dica: 'Ave que enxerga bem de noite' },
  { id: 'm25', palavra: 'MORCEGO',     categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'medio', emoji: '🦇', dica: 'Voa de cabeça pra baixo dormindo' },
  { id: 'm26', palavra: 'BORBOLETA',   categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'medio', emoji: '🦋', dica: 'Já foi lagarta antes de ganhar asas coloridas' },
  { id: 'm27', palavra: 'HIPOPOTAMO',  categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'medio', emoji: '🦛', dica: 'Enorme, vive em rio de água doce na África' },
  { id: 'm28', palavra: 'CARANGUEJO',  categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'medio', emoji: '🦀', dica: 'Anda de lado e tem duas pinças' },
  { id: 'm29', palavra: 'LAGOSTA',     categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'medio', emoji: '🦞', dica: 'Fica vermelha depois de cozida' },
  { id: 'm30', palavra: 'ESQUILO',     categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'medio', emoji: '🐿️', dica: 'Guarda castanha e sobe em árvore' },
  { id: 'm31', palavra: 'MORANGO',     categoria: CATEGORIAS.COMIDAS,    dificuldade: 'medio', emoji: '🍓', dica: 'Fruta vermelha com pontinhos' },
  { id: 'm32', palavra: 'MAMAO',       categoria: CATEGORIAS.COMIDAS,    dificuldade: 'medio', emoji: '🥭', dica: 'Fruta alaranjada e bem mole por dentro' },
  { id: 'm33', palavra: 'MARACUJA',    categoria: CATEGORIAS.COMIDAS,    dificuldade: 'medio', emoji: '🟡', dica: 'Fruta azeda usada em suco calmante' },
  { id: 'm34', palavra: 'LASANHA',     categoria: CATEGORIAS.COMIDAS,    dificuldade: 'medio', emoji: '🍝', dica: 'Prato em camadas com massa e molho' },
  { id: 'm35', palavra: 'HAMBURGUER',  categoria: CATEGORIAS.COMIDAS,    dificuldade: 'medio', emoji: '🍔', dica: 'Pão, carne e salada empilhados' },
  { id: 'm36', palavra: 'CACHORROQUENTE', categoria: CATEGORIAS.COMIDAS, dificuldade: 'medio', emoji: '🌭', dica: 'Salsicha dentro do pão (tudo junto, sem hífen)' },
  { id: 'm37', palavra: 'PIPOCA',      categoria: CATEGORIAS.COMIDAS,    dificuldade: 'medio', emoji: '🍿', dica: 'Estoura no fogo, ótima pro cinema' },
  { id: 'm38', palavra: 'PANQUECA',    categoria: CATEGORIAS.COMIDAS,    dificuldade: 'medio', emoji: '🥞', dica: 'Redonda, empilhada, com mel ou xarope' },
  { id: 'm39', palavra: 'MACARRAO',    categoria: CATEGORIAS.COMIDAS,    dificuldade: 'medio', emoji: '🍜', dica: 'Fininho ou grosso, sempre com molho' },
  { id: 'm40', palavra: 'GELADEIRA',   categoria: CATEGORIAS.OBJETOS,    dificuldade: 'medio', emoji: '🧊', dica: 'Mantém a comida gelada em casa' },
  { id: 'm41', palavra: 'ASPIRADOR',   categoria: CATEGORIAS.OBJETOS,    dificuldade: 'medio', emoji: '🧹', dica: 'Suga a poeira do chão' },
  { id: 'm42', palavra: 'LANTERNA',    categoria: CATEGORIAS.OBJETOS,    dificuldade: 'medio', emoji: '🔦', dica: 'Ilumina quando falta luz' },
  { id: 'm43', palavra: 'MOCHILA',     categoria: CATEGORIAS.OBJETOS,    dificuldade: 'medio', emoji: '🎒', dica: 'Carrega nas costas, cheia de livro' },
  { id: 'm44', palavra: 'VASSOURA',    categoria: CATEGORIAS.OBJETOS,    dificuldade: 'medio', emoji: '🧹', dica: 'Varre a sujeira do chão' },
  { id: 'm45', palavra: 'TERMOMETRO',  categoria: CATEGORIAS.OBJETOS,    dificuldade: 'medio', emoji: '🌡️', dica: 'Mede a febre ou a temperatura' },
  { id: 'm46', palavra: 'FURACAO',     categoria: CATEGORIAS.NATUREZA,   dificuldade: 'medio', emoji: '🌀', dica: 'Vento muito forte que gira' },
  { id: 'm47', palavra: 'ARCOIRIS',    categoria: CATEGORIAS.NATUREZA,   dificuldade: 'medio', emoji: '🌈', dica: 'Aparece no céu depois da chuva (sem hífen)' },
  { id: 'm48', palavra: 'GEISER',      categoria: CATEGORIAS.NATUREZA,   dificuldade: 'medio', emoji: '💨', dica: 'Jato de água quente saindo do chão' },
  { id: 'm49', palavra: 'DESERTO',     categoria: CATEGORIAS.NATUREZA,   dificuldade: 'medio', emoji: '🏜️', dica: 'Bem seco, cheio de areia e pouca chuva' },
  { id: 'm50', palavra: 'FLORESTA',    categoria: CATEGORIAS.NATUREZA,   dificuldade: 'medio', emoji: '🌲', dica: 'Muitas árvores juntas' },
  { id: 'm51', palavra: 'MOTORISTA',   categoria: CATEGORIAS.PROFISSOES, dificuldade: 'medio', emoji: '🚕', dica: 'Dirige o veículo profissionalmente' },
  { id: 'm52', palavra: 'PROFESSOR',   categoria: CATEGORIAS.PROFISSOES, dificuldade: 'medio', emoji: '👨‍🏫', dica: 'Ensina os alunos na escola' },
  { id: 'm53', palavra: 'COZINHEIRO',  categoria: CATEGORIAS.PROFISSOES, dificuldade: 'medio', emoji: '👨‍🍳', dica: 'Prepara a comida do restaurante' },
  { id: 'm54', palavra: 'ELETRICISTA', categoria: CATEGORIAS.PROFISSOES, dificuldade: 'medio', emoji: '💡', dica: 'Mexe com fio e instalação elétrica' },
  { id: 'm55', palavra: 'JARDINEIRO',  categoria: CATEGORIAS.PROFISSOES, dificuldade: 'medio', emoji: '🌱', dica: 'Cuida das plantas e do jardim' },
  { id: 'm56', palavra: 'FUTEBOL',     categoria: CATEGORIAS.ESPORTES,   dificuldade: 'medio', emoji: '⚽', dica: 'Esporte mais popular do Brasil' },
  { id: 'm57', palavra: 'VOLEIBOL',    categoria: CATEGORIAS.ESPORTES,   dificuldade: 'medio', emoji: '🏐', dica: 'Joga com a rede no meio da quadra' },
  { id: 'm58', palavra: 'GINASTICA',   categoria: CATEGORIAS.ESPORTES,   dificuldade: 'medio', emoji: '🤸', dica: 'Exige muita flexibilidade e equilíbrio' },
  { id: 'm59', palavra: 'PATINACAO',   categoria: CATEGORIAS.ESPORTES,   dificuldade: 'medio', emoji: '⛸️', dica: 'Desliza sobre rodinhas ou gelo' },
  { id: 'm60', palavra: 'FAZENDA',     categoria: CATEGORIAS.LUGARES,    dificuldade: 'medio', emoji: '🚜', dica: 'Tem plantação e animais soltos' },
  { id: 'm61', palavra: 'AEROPORTO',   categoria: CATEGORIAS.LUGARES,    dificuldade: 'medio', emoji: '🛫', dica: 'De onde os aviões decolam' },
  { id: 'm62', palavra: 'HOSPITAL',    categoria: CATEGORIAS.LUGARES,    dificuldade: 'medio', emoji: '🏥', dica: 'Onde os médicos cuidam dos pacientes' },
  { id: 'm63', palavra: 'PADARIA',     categoria: CATEGORIAS.LUGARES,    dificuldade: 'medio', emoji: '🥐', dica: 'Cheira a pão quentinho' },
  { id: 'm64', palavra: 'JAQUETA',     categoria: CATEGORIAS.ROUPAS,     dificuldade: 'medio', emoji: '🧥', dica: 'Veste por cima pra não sentir frio' },
  { id: 'm65', palavra: 'CHINELO',     categoria: CATEGORIAS.ROUPAS,     dificuldade: 'medio', emoji: '🩴', dica: 'Calçado simples de praia' },
  { id: 'm66', palavra: 'OCULOS',      categoria: CATEGORIAS.ROUPAS,     dificuldade: 'medio', emoji: '👓', dica: 'Ajuda quem não enxerga bem' },
  { id: 'm67', palavra: 'PULSEIRA',    categoria: CATEGORIAS.ROUPAS,     dificuldade: 'medio', emoji: '📿', dica: 'Acessório que se usa no pulso' },
  { id: 'm68', palavra: 'TECLADO',     categoria: CATEGORIAS.TECNOLOGIA, dificuldade: 'medio', emoji: '⌨️', dica: 'Cheio de teclas pra digitar' },
  { id: 'm69', palavra: 'IMPRESSORA',  categoria: CATEGORIAS.TECNOLOGIA, dificuldade: 'medio', emoji: '🖨️', dica: 'Passa o que está na tela pro papel' },
  { id: 'm70', palavra: 'CARREGADOR',  categoria: CATEGORIAS.TECNOLOGIA, dificuldade: 'medio', emoji: '🔌', dica: 'Sem ele o celular fica sem bateria' },

  // -------------------------------------------------------------- DIFÍCIL
  { id: 'd01', palavra: 'ORNITORRINCO',   categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'dificil', emoji: '🦆', dica: 'Bico de pato, põe ovo, mas é mamífero' },
  { id: 'd02', palavra: 'RINOCERONTE',    categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'dificil', emoji: '🦏', dica: 'Tem chifre no nariz' },
  { id: 'd03', palavra: 'CAMALEAO',       categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'dificil', emoji: '🦎', dica: 'Muda de cor pra se esconder' },
  { id: 'd04', palavra: 'ESCORPIAO',      categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'dificil', emoji: '🦂', dica: 'Ferrão no final do rabo' },
  { id: 'd05', palavra: 'BERINJELA',      categoria: CATEGORIAS.COMIDAS,    dificuldade: 'dificil', emoji: '🍆', dica: 'Legume roxo comprido' },
  { id: 'd06', palavra: 'ESTROGONOFE',    categoria: CATEGORIAS.COMIDAS,    dificuldade: 'dificil', emoji: '🍲', dica: 'Prato com creme de leite e batata palha' },
  { id: 'd07', palavra: 'BRIGADEIRO',     categoria: CATEGORIAS.COMIDAS,    dificuldade: 'dificil', emoji: '🍬', dica: 'Doce de festa feito de chocolate' },
  { id: 'd08', palavra: 'MICROSCOPIO',    categoria: CATEGORIAS.OBJETOS,    dificuldade: 'dificil', emoji: '🔬', dica: 'Mostra o que é pequeno demais pro olho' },
  { id: 'd09', palavra: 'AMPULHETA',      categoria: CATEGORIAS.OBJETOS,    dificuldade: 'dificil', emoji: '⏳', dica: 'Mede o tempo com areia' },
  { id: 'd10', palavra: 'CALCULADORA',    categoria: CATEGORIAS.OBJETOS,    dificuldade: 'dificil', emoji: '🧮', dica: 'Resolve conta pra você' },
  { id: 'd11', palavra: 'SUBMARINO',      categoria: CATEGORIAS.TRANSPORTE, dificuldade: 'dificil', emoji: '🛥️', dica: 'Anda debaixo da água' },
  { id: 'd12', palavra: 'AMBULANCIA',     categoria: CATEGORIAS.TRANSPORTE, dificuldade: 'dificil', emoji: '🚑', dica: 'Corre com a sirene ligada levando paciente' },
  { id: 'd13', palavra: 'TERREMOTO',      categoria: CATEGORIAS.NATUREZA,   dificuldade: 'dificil', emoji: '🌐', dica: 'A terra treme' },
  { id: 'd14', palavra: 'RELAMPAGO',      categoria: CATEGORIAS.NATUREZA,   dificuldade: 'dificil', emoji: '⚡', dica: 'Clarão no céu antes do trovão' },
  { id: 'd15', palavra: 'ARQUITETO',      categoria: CATEGORIAS.PROFISSOES, dificuldade: 'dificil', emoji: '📐', dica: 'Desenha o projeto da casa' },
  { id: 'd16', palavra: 'VETERINARIO',    categoria: CATEGORIAS.PROFISSOES, dificuldade: 'dificil', emoji: '🐾', dica: 'Médico de bicho' },
  { id: 'd17', palavra: 'ASTRONAUTA',     categoria: CATEGORIAS.PROFISSOES, dificuldade: 'dificil', emoji: '👨‍🚀', dica: 'Trabalha flutuando' },
  { id: 'd18', palavra: 'PARAQUEDISMO',   categoria: CATEGORIAS.ESPORTES,   dificuldade: 'dificil', emoji: '🪂', dica: 'Pula do avião de propósito' },
  { id: 'd19', palavra: 'BIBLIOTECA',     categoria: CATEGORIAS.LUGARES,    dificuldade: 'dificil', emoji: '🏛️', dica: 'Lugar cheio de livro e silêncio' },
  { id: 'd20', palavra: 'LABIRINTO',      categoria: CATEGORIAS.LUGARES,    dificuldade: 'dificil', emoji: '🌀', dica: 'Fácil entrar, difícil sair' },
  { id: 'd21', palavra: 'CHIMPANZE',      categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'dificil', emoji: '🦍', dica: 'Primata bem parecido conosco geneticamente' },
  { id: 'd22', palavra: 'CENTOPEIA',      categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'dificil', emoji: '🐛', dica: 'Bicho comprido com um monte de perninhas' },
  { id: 'd23', palavra: 'LIBELULA',       categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'dificil', emoji: '🦟', dica: 'Inseto de asas finas que voa sobre a água' },
  { id: 'd24', palavra: 'FLAMINGO',       categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'dificil', emoji: '🦩', dica: 'Ave rosa que fica em pé numa perna só' },
  { id: 'd25', palavra: 'ARARAAZUL',      categoria: CATEGORIAS.ANIMAIS,    dificuldade: 'dificil', emoji: '🦜', dica: 'Ave brasileira colorida e falante (tudo junto)' },
  { id: 'd26', palavra: 'CARAMBOLA',      categoria: CATEGORIAS.COMIDAS,    dificuldade: 'dificil', emoji: '⭐', dica: 'Fruta que parece uma estrela quando fatiada' },
  { id: 'd27', palavra: 'ALCACHOFRA',     categoria: CATEGORIAS.COMIDAS,    dificuldade: 'dificil', emoji: '🥬', dica: 'Legume de folhas duras em formato de flor' },
  { id: 'd28', palavra: 'FEIJOADA',       categoria: CATEGORIAS.COMIDAS,    dificuldade: 'dificil', emoji: '🍛', dica: 'Prato brasileiro tradicional de sábado' },
  { id: 'd29', palavra: 'CAPUCCINO',      categoria: CATEGORIAS.COMIDAS,    dificuldade: 'dificil', emoji: '☕', dica: 'Café com espuma de leite por cima' },
  { id: 'd30', palavra: 'GUARANA',        categoria: CATEGORIAS.COMIDAS,    dificuldade: 'dificil', emoji: '🥤', dica: 'Refrigerante bem brasileiro, feito de fruta amazônica' },
  { id: 'd31', palavra: 'ESTETOSCOPIO',   categoria: CATEGORIAS.OBJETOS,    dificuldade: 'dificil', emoji: '🩺', dica: 'O médico usa pra escutar seu coração' },
  { id: 'd32', palavra: 'LIQUIDIFICADOR', categoria: CATEGORIAS.OBJETOS,    dificuldade: 'dificil', emoji: '🥤', dica: 'Bate a vitamina e a fruta na cozinha' },
  { id: 'd33', palavra: 'EXTINTOR',       categoria: CATEGORIAS.OBJETOS,    dificuldade: 'dificil', emoji: '🧯', dica: 'Apaga o fogo em caso de incêndio' },
  { id: 'd34', palavra: 'BUSSOLA',        categoria: CATEGORIAS.OBJETOS,    dificuldade: 'dificil', emoji: '🧭', dica: 'Mostra pra onde fica o norte' },
  { id: 'd35', palavra: 'CANDELABRO',     categoria: CATEGORIAS.OBJETOS,    dificuldade: 'dificil', emoji: '🕯️', dica: 'Suporte enfeitado pra várias velas' },
  { id: 'd36', palavra: 'ESTALACTITE',    categoria: CATEGORIAS.NATUREZA,   dificuldade: 'dificil', emoji: '🪨', dica: 'Pendura do teto de uma caverna, formada por gotejamento' },
  { id: 'd37', palavra: 'AVALANCHE',      categoria: CATEGORIAS.NATUREZA,   dificuldade: 'dificil', emoji: '🏔️', dica: 'Neve descendo a montanha de uma vez' },
  { id: 'd38', palavra: 'MARESIA',        categoria: CATEGORIAS.NATUREZA,   dificuldade: 'dificil', emoji: '🌊', dica: 'Aquele cheiro característico perto do mar' },
  { id: 'd39', palavra: 'CONSTELACAO',    categoria: CATEGORIAS.NATUREZA,   dificuldade: 'dificil', emoji: '✨', dica: 'Desenho formado por estrelas no céu' },
  { id: 'd40', palavra: 'ARQUIPELAGO',    categoria: CATEGORIAS.NATUREZA,   dificuldade: 'dificil', emoji: '🏝️', dica: 'Conjunto de várias ilhas próximas' },
  { id: 'd41', palavra: 'FISIOTERAPEUTA', categoria: CATEGORIAS.PROFISSOES, dificuldade: 'dificil', emoji: '🦴', dica: 'Ajuda a recuperar o movimento do corpo' },
  { id: 'd42', palavra: 'PROGRAMADOR',    categoria: CATEGORIAS.PROFISSOES, dificuldade: 'dificil', emoji: '💻', dica: 'Escreve código pra fazer sistemas funcionarem' },
  { id: 'd43', palavra: 'ENGENHEIRO',     categoria: CATEGORIAS.PROFISSOES, dificuldade: 'dificil', emoji: '👷', dica: 'Projeta e calcula estruturas e máquinas' },
  { id: 'd44', palavra: 'PALEONTOLOGO',   categoria: CATEGORIAS.PROFISSOES, dificuldade: 'dificil', emoji: '🦴', dica: 'Estuda fóssil de dinossauro' },
  { id: 'd45', palavra: 'ODONTOLOGISTA',  categoria: CATEGORIAS.PROFISSOES, dificuldade: 'dificil', emoji: '🦷', dica: 'Cuida dos seus dentes' },
  { id: 'd46', palavra: 'HALTEROFILISMO', categoria: CATEGORIAS.ESPORTES,   dificuldade: 'dificil', emoji: '🏋️', dica: 'Esporte de levantar peso o mais pesado possível' },
  { id: 'd47', palavra: 'ARREMESSODEPESO',categoria: CATEGORIAS.ESPORTES,   dificuldade: 'dificil', emoji: '🥎', dica: 'Atleta lança uma bola de metal o mais longe possível (tudo junto)' },
  { id: 'd48', palavra: 'MARATONA',       categoria: CATEGORIAS.ESPORTES,   dificuldade: 'dificil', emoji: '🏃', dica: 'Corrida de mais de 40 quilômetros' },
  { id: 'd49', palavra: 'PLANETARIO',     categoria: CATEGORIAS.LUGARES,    dificuldade: 'dificil', emoji: '🔭', dica: 'Cúpula que projeta estrelas e planetas' },
  { id: 'd50', palavra: 'OBSERVATORIO',   categoria: CATEGORIAS.LUGARES,    dificuldade: 'dificil', emoji: '🔭', dica: 'Tem telescópio gigante pra ver o céu' },
  { id: 'd51', palavra: 'ANFITEATRO',     categoria: CATEGORIAS.LUGARES,    dificuldade: 'dificil', emoji: '🏟️', dica: 'Construção em formato de meia lua pra plateia' },
  { id: 'd52', palavra: 'INTELIGENCIAARTIFICIAL', categoria: CATEGORIAS.TECNOLOGIA, dificuldade: 'dificil', emoji: '🤖', dica: 'Sigla IA, é o que responde suas perguntas por chat (tudo junto)' },
  { id: 'd53', palavra: 'FONEDEOUVIDO',   categoria: CATEGORIAS.TECNOLOGIA, dificuldade: 'dificil', emoji: '🎧', dica: 'Você usa pra escutar música sem incomodar ninguém (tudo junto)' },
  { id: 'd54', palavra: 'SMARTWATCH',     categoria: CATEGORIAS.TECNOLOGIA, dificuldade: 'dificil', emoji: '⌚', dica: 'Relógio que conta passos e mostra notificação' },
]

/** Lista de categorias que realmente aparecem no banco (pra montar filtro na tela). */
export const CATEGORIAS_DISPONIVEIS = [...new Set(PALAVRAS.map((p) => p.categoria))].sort()
